//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterselMCVProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InterselDBEntities : DbContext
    {
        public InterselDBEntities()
            : base("name=InterselDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhoneDetail> PhoneDetail { get; set; }
        public virtual DbSet<PhoneLine> PhoneLine { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int LOGINSP(string tagUsuario, string clave)
        {
            var tagUsuarioParameter = tagUsuario != null ?
                new ObjectParameter("TagUsuario", tagUsuario) :
                new ObjectParameter("TagUsuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOGINSP", tagUsuarioParameter, claveParameter);
        }
    }
}
