//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterselMCVProject.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PhoneDetail
    {
        public int CallDetailId { get; set; }
        public string MobileLine { get; set; }
        public string CalledPartyNumber { get; set; }
        public string CalledPartyDescription { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Duration { get; set; }
        public decimal TotalCost { get; set; }

        public string GetDurationDif()
        {
            return TimeSpan.FromSeconds(this.Duration).ToString();
        }
        public string GetTimeCall() 
        {
            return DateTime.ToString("hh:mm:ss");
        }
        public string GetDateCall()
        {
            return DateTime.ToString("dd/MM/yyyy");
        }
        public string GetTotalCostPrice() 
        {
            return $"${this.TotalCost}";
        }
    }
}
