//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterselMCVProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int idUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string TagUsuario { get; set; }
        public string Clave { get; set; }
        public Nullable<TipoUsuario> TipoUsuario { get; set; }
        public Nullable<URoles> Rol { get; set; }
        public string MobileLine { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
